In [1]:
import torch
from torch import nn
from torch import optim

In [2]:
inputs  = torch.tensor([[0.0,0.0],[0.0,1.0],[1.0,0.0],[1.0,1.0]])
outputs = torch.tensor([0,1,1,0]).view(-1, 1).float()

In [3]:
outputs

tensor([[0.],
        [1.],
        [1.],
        [0.]])

In [4]:
class Xor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(2,8),
            nn.Tanh(),
            nn.Linear(8,1)
        )

    def forward(self,x):
        return self.network(x)

In [5]:
model = Xor().to("cpu")
print(model)

Xor(
  (network): Sequential(
    (0): Linear(in_features=2, out_features=8, bias=True)
    (1): Tanh()
    (2): Linear(in_features=8, out_features=1, bias=True)
  )
)


In [6]:
lr = 0.2
epochs = 5000

In [7]:
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(
    model.parameters(),
    lr = lr 
)

In [8]:
for i in range(epochs):
    model.train()
    predictions = model(inputs)
    loss = criterion(predictions, outputs)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if i % 500 == 0:
        print(f"Epoch {i}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 0.6959
Epoch 500, Loss: 0.0001
Epoch 1000, Loss: 0.0000
Epoch 1500, Loss: 0.0000
Epoch 2000, Loss: 0.0000
Epoch 2500, Loss: 0.0000
Epoch 3000, Loss: 0.0000
Epoch 3500, Loss: 0.0000
Epoch 4000, Loss: 0.0000
Epoch 4500, Loss: 0.0000


In [9]:
model.eval()

with torch.no_grad():
    probs = torch.sigmoid(model(inputs))
    print(probs)
    print((probs > 0.5).int())

tensor([[2.3268e-07],
        [1.0000e+00],
        [1.0000e+00],
        [1.5737e-06]])
tensor([[0],
        [1],
        [1],
        [0]], dtype=torch.int32)
